### ISSUE TITLE
Can't run bankai binary from npm scripts with nvm

### ISSUE THREAD

**Issue by eugeneware** [yoshuawuyts/bankai#133]
When using `nvm`, when I try to run `bankai` from my `./node_modules/.bin` folder (ie. when installed as a local `dev` dependency) or from an `npm run <script>` I get this error:

``` bash
$ ./node_modules/.bin/bankai
/Users/eugeneware/Dropbox/work/scratch/choo-incdec/node_modules/resolve/lib/sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
    ^

Error: Cannot find module './index.js' from '/Users/eugeneware/Dropbox/work/scratch/choo-incdec'
    at Function.module.exports [as sync] (/Users/eugeneware/Dropbox/work/scratch/choo-incdec/node_modules/resolve/lib/sync.js:33:11)
    at main (/Users/eugeneware/Dropbox/work/scratch/choo-incdec/node_modules/bankai/bin.js:82:23)
    at Object.<anonymous> (/Users/eugeneware/Dropbox/work/scratch/choo-incdec/node_modules/bankai/bin.js:73:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
```

I've tested this in linux and mac OS X. I'm running node v7.7.7, but it seems to happen on earlier version of node. I'm running npm v4.1.2.

**Comment by eugeneware** [comment]
My mistake. The error means that it can't find an index.js in my current folder. Sorry!
