### ISSUE TITLE
"bankai --help" doesn't work if index.js is not present

### ISSUE THREAD

**Issue by noffle** [yoshuawuyts/bankai#135]
```
[sww@figure8 tmp]$ bankai -h
/home/sww/.npm-global/lib/node_modules/bankai/node_modules/resolve/lib/sync.js:39
    throw err;
    ^

Error: Cannot find module './index.js' from '/tmp'
    at Function.module.exports [as sync] (/home/sww/.npm-global/lib/node_modules/bankai/node_modules/resolve/lib/sync.js:37:15)
    at main (/home/sww/.npm-global/lib/node_modules/bankai/bin.js:82:23)
    at Object.<anonymous> (/home/sww/.npm-global/lib/node_modules/bankai/bin.js:73:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
[sww@figure8 tmp]$ touch index.js
[sww@figure8 tmp]$ bankai -h

  Usage:
    $ bankai <command> [options]
...
```

**Comment by yoshuawuyts** [comment]
lol

**Comment by yoshuawuyts** [comment]
`v5.5.1`
