### ISSUE TITLE
bankai@5.5.0: requesting an asset causes crash

### ISSUE THREAD

**Issue by noffle** [yoshuawuyts/bankai#136]
In this case I was trying to serve `bunny.png` from the current directory. The process crashes with the following after the request for `/bunny.png` is received. This is a regression from `5.4.0` -- I downgraded to that for now, which seems to work fine.

```
[sww@figure8 BoardingAction]$ bankai -a . game.js
17:48:25 ✨  bankai Started for game.js on http://localhost:8080
17:48:25 ✨  http req /
17:48:25 ✨  http res / GET:200 46ms 242B
17:48:25 ✨  http req /bundle.css
17:48:26 ✨  http req /bundle.js
17:48:36 ✨  http res /bundle.css GET:200 10954ms
17:48:36 ✨  http res /bundle.js GET:200 10965ms 1.3 MB
17:48:38 ✨  http req /bunny.png
/home/sww/.npm-global/lib/node_modules/bankai/node_modules/send/index.js:873
  if (this._acceptRanges && !res.getHeader('Accept-Ranges')) {
                                 ^

TypeError: res.getHeader is not a function
    at SendStream.setHeader (/home/sww/.npm-global/lib/node_modules/bankai/node_modules/send/index.js:873:34)
    at SendStream.send (/home/sww/.npm-global/lib/node_modules/bankai/node_modules/send/index.js:632:8)
    at onstat (/home/sww/.npm-global/lib/node_modules/bankai/node_modules/send/index.js:737:10)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

**Comment by lrlna** [comment]
having the same issue actually; gonna dig in
